# Generated by Django 4.1.7 on 2023-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
