# Generated by Django 4.1.7 on 2023-03-01 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0003_alter_fileupload_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('link_duration', models.IntegerField(default=300, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)])),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_uploader.fileupload')),
            ],
        ),
    ]
