# Generated by Django 4.1.7 on 2023-03-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0005_generatelink_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatelink',
            name='link',
        ),
        migrations.AddField(
            model_name='generatelink',
            name='create_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
