# Generated by Django 4.1.7 on 2023-03-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0006_remove_generatelink_link_generatelink_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatelink',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
